@echo off
rem ......................
echo Setup enviroment - Expect z88dk 1.99c on c:\z88dk
rem ......................
call setenv.bat
rem ......................
echo Building TAP
rem ......................
utils\bas2tap -a10 -sPARSER loader.bas loader.tap > nul
rem .....-................
echo Packing Loading Screen
rem ......................
appmake +zx -b screen.scr -o screen.tap --blockname loading --org 16384 --noloader		
rem .....-................
echo Compiling Game Main code
rem ......................
zcc +zx -vn -SO3 -startup=1 -clib=sdcc_iy --max-allocs-per-node200000 nirvanadem.c btile.asm -o nirvanadem
appmake +zx -b nirvanadem_NIRVANAP.bin -o nirvanap.tap --noloader --org 56323 --blockname NIRVANAP
appmake +zx -b nirvanadem_CODE.bin -o nirvanadem.tap --noloader --org 32768 --blockname nirvanadem
rem .....-................
echo Packing Taps
rem ......................
copy /b loader.tap + screen.tap + nirvanap.tap + nirvanadem.tap demo.tap
rem ......................
rem # Clean Temporary Stuff
rem ......................
del loader.tap
del screen.tap
del nirvanap.tap
del nirvanadem.tap
del *.bin

echo Done enjoy!
